require("source.aircraft")

describe("Aircraft", function()
  describe("Aircraft.new", function()
    it("sets callsign, fuel, fuel_max, altitude, and situation", function()
      local a = Aircraft.new("GA4", 90, 8000, "Normal")
      assert.equal("GA4", a.callsign)
      assert.equal(90, a.fuel)
      assert.equal(90, a.fuel_max)
      assert.equal(8000, a.altitude)
      assert.equal("Normal", a.situation)
    end)

    it("leaves time_remaining nil when time_limit is not provided", function()
      local a = Aircraft.new("GA4", 90, 8000, "Normal")
      assert.is_nil(a.time_remaining)
    end)

    it("sets time_remaining when time_limit is provided", function()
      local a = Aircraft.new("GCS1", 85, 2500, "Medical", nil, 75)
      assert.equal(75, a.time_remaining)
    end)
  end)

  describe("Aircraft.tick", function()
    it("decreases fuel by dt", function()
      local a = Aircraft.new("GA4", 90, 8000, "Normal")
      Aircraft.tick(a, 1)
      assert.equal(89, a.fuel)
    end)

    it("clamps fuel at 0", function()
      local a = Aircraft.new("GA4", 0.5, 8000, "Normal")
      Aircraft.tick(a, 1)
      assert.equal(0, a.fuel)
    end)

    -- regression guard — tick does not mutate fuel_max
    it("does not mutate fuel_max", function()
      local a = Aircraft.new("GA4", 90, 8000, "Normal")
      Aircraft.tick(a, 10)
      assert.equal(90, a.fuel_max)
    end)

    it("decreases time_remaining by dt when present", function()
      local a = Aircraft.new("GCS1", 85, 2500, "Medical", nil, 75)
      Aircraft.tick(a, 1)
      assert.equal(74, a.time_remaining)
    end)

    it("clamps time_remaining at 0", function()
      local a = Aircraft.new("GCS1", 85, 2500, "Medical", nil, 0.5)
      Aircraft.tick(a, 1)
      assert.equal(0, a.time_remaining)
    end)

    it("does not modify time_remaining when nil", function()
      local a = Aircraft.new("GA4", 90, 8000, "Normal")
      Aircraft.tick(a, 1)
      assert.is_nil(a.time_remaining)
    end)
  end)

  describe("Aircraft.is_out_of_fuel", function()
    it("returns false when fuel > 0", function()
      local a = Aircraft.new("GA4", 90, 8000, "Normal")
      assert.is_false(Aircraft.is_out_of_fuel(a))
    end)

    it("returns true when fuel == 0", function()
      local a = Aircraft.new("GA4", 0, 8000, "Normal")
      assert.is_true(Aircraft.is_out_of_fuel(a))
    end)
  end)

  describe("Aircraft.is_time_expired", function()
    it("returns false when time_remaining is nil (normal aircraft)", function()
      local a = Aircraft.new("GA4", 90, 8000, "Normal")
      assert.is_false(Aircraft.is_time_expired(a))
    end)

    it("returns false when time_remaining is positive", function()
      local a = Aircraft.new("GCS1", 85, 2500, "Medical", nil, 75)
      assert.is_false(Aircraft.is_time_expired(a))
    end)

    it("returns true when time_remaining is 0", function()
      local a = Aircraft.new("GCS1", 85, 2500, "Medical", nil, 0)
      assert.is_true(Aircraft.is_time_expired(a))
    end)
  end)
end)
